version: "1"
services:
  zookeeper:
    container_name: zookeeperContainer
    image: bitnami/zookeeper:latest
    network_mode: bridge
    ports:
      - "2181:2181"
    volumes:
      - "/data/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafkaContainer
    image: bitnami/kafka:latest
    network_mode: bridge
    ports:
      - "9092:9092"
    volumes:
      - "/data/bitnami/kafka"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    links:
      - zookeeper
  
